controller_joint_names: ['prismatic', 'r1', 'r2', 'r3', 'r4', 'r5', ]
jlr23:

   # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

 # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: prismatic
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: r1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: r2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: r3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: r4
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: r5
    pid: {p: 100.0, i: 0.01, d: 10.0}
